SpaceInsideBrackets:
  Enabled: false
LineLength:
  Description: Limit lines to 100 characters.
  Max: 120
EmptyLinesAroundBody:
  Enabled: false
StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true
